// <auto-generated />
using DemoProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoProject.Migrations
{
    [DbContext(typeof(DemoProjectContext))]
    [Migration("20240322014538_AdditionalSeedData")]
    partial class AdditionalSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DemoProject.Models.ClassRoom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int")
                        .HasColumnName("room_number");

                    b.HasKey("ID");

                    b.ToTable("classroom");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            RoomNumber = 101
                        },
                        new
                        {
                            ID = -2,
                            RoomNumber = 102
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClassID")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("last_name");

                    b.HasKey("ID");

                    b.HasIndex("ClassID")
                        .HasDatabaseName("FK_Student_ClassRoom");

                    b.ToTable("student");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            ClassID = -1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = -2,
                            ClassID = -1,
                            FirstName = "Jane",
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = -3,
                            ClassID = -1,
                            FirstName = "Tom",
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = -4,
                            ClassID = -2,
                            FirstName = "Bob",
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = -5,
                            ClassID = -2,
                            FirstName = "Joe",
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = -6,
                            ClassID = -2,
                            FirstName = "Paul",
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("DemoProject.Models.Student", b =>
                {
                    b.HasOne("DemoProject.Models.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Student_ClassRoom");

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("DemoProject.Models.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
